"""
CoordinationEvent — standard schema for cross-domain coordination signals.

Mirrors schemas/coordination_event.json in AfriKaziOS.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class EventSeverity(str, Enum):
    INFO     = "info"
    WARNING  = "warning"
    ALERT    = "alert"
    CRITICAL = "critical"


class EventDomain(str, Enum):
    HEALTH       = "health"
    WATER        = "water"
    AGRICULTURE  = "agriculture"
    ENERGY       = "energy"
    TRANSPORT    = "transport"
    EDUCATION    = "education"
    PROCUREMENT  = "procurement"
    FINANCE      = "finance"
    CIVIC        = "civic"


class EventReality(str, Enum):
    """Is this a real signal or synthetic/demo data?

    Trust integrity made structural: instead of sniffing a "DEMO —" prefix out
    of a free-text field, producers declare reality explicitly. Default is REAL
    because a live coordination fabric that silently defaulted to DEMO would have
    its genuine alerts marked as exercises and ignored — the dangerous failure.
    The contract is therefore: synthetic *generators* must set DEMO.
    """
    REAL = "real"
    DEMO = "demo"


class EventConfidence(str, Enum):
    """Epistemic status of the signal — the Confirmed/Probable/Speculative ladder.

    Default is UNKNOWN, not PROBABLE: undeclared confidence is unknown, never
    assumed. Downstream consumers (and the CAP exporter's certainty field) read
    this to decide how hard to act on a signal.
    """
    CONFIRMED   = "confirmed"
    PROBABLE    = "probable"
    SPECULATIVE = "speculative"
    UNKNOWN     = "unknown"


@dataclass
class SubnationalLocation:
    """Country-neutral subnational location (G10 fix, v0.3.0).

    Two generic admin levels cover the region's structures: county/sub-county
    (KE), mkoa/wilaya (TZ), district/county (UG), province/district (RW).
    `country` is ISO 3166-1 alpha-2. Kenya-compatible read accessors are
    provided so existing consumers written against `.county` keep working
    whichever type flows through the bus.
    """
    country: str = ""
    admin_1: str = ""
    admin_1_code: int = 0
    admin_2: str = ""
    lat: float = 0.0
    lon: float = 0.0

    # Kenya-era compatibility accessors (read-only)
    @property
    def county(self) -> str:
        return self.admin_1

    @property
    def county_code(self) -> int:
        return self.admin_1_code

    @property
    def sub_county(self) -> str:
        return self.admin_2

    @classmethod
    def tanzania(cls, region: str = "", district: str = "",
                 lat: float = 0.0, lon: float = 0.0) -> SubnationalLocation:
        """Convenience: mkoa (region) / wilaya (district)."""
        return cls(country="TZ", admin_1=region, admin_2=district, lat=lat, lon=lon)

    def to_dict(self) -> dict:
        return {k: v for k, v in self.__dict__.items() if v}


@dataclass
class KenyaLocation:
    """Kenya-specific location with county code (1-47).

    Retained unchanged for backwards compatibility (see tanzania.py port
    notes / Gap Register G10). New country-neutral producers should prefer
    SubnationalLocation; consumers can rely on the shared accessors
    (.admin_1/.admin_2/.country) present on both types.
    """
    county: str = ""
    county_code: int = 0
    sub_county: str = ""
    lat: float = 0.0
    lon: float = 0.0

    # Forward-compatibility accessors mirroring SubnationalLocation
    @property
    def country(self) -> str:
        return "KE"

    @property
    def admin_1(self) -> str:
        return self.county

    @property
    def admin_1_code(self) -> int:
        return self.county_code

    @property
    def admin_2(self) -> str:
        return self.sub_county

    def to_subnational(self) -> SubnationalLocation:
        return SubnationalLocation(country="KE", admin_1=self.county,
                                   admin_1_code=self.county_code,
                                   admin_2=self.sub_county,
                                   lat=self.lat, lon=self.lon)

    def to_dict(self) -> dict:
        return {k: v for k, v in self.__dict__.items() if v}


@dataclass
class CoordinationEvent:
    """
    A coordination signal crossing domain boundaries.

    Generated by any MCP server or sensor. Consumed by downstream
    domain handlers that need to act on the signal.

    Example — drought cascade:
      CoordinationEvent(
          domain=EventDomain.WATER,
          event_type="drought_alert",
          severity=EventSeverity.ALERT,
          location=KenyaLocation(county="Turkana", county_code=23),
          source="wapimaji-mcp",
          data={
              "ndvi_anomaly": -0.28,
              "spi_3month": -1.8,
              "rainfall_deficit_pct": 42,
          },
          cross_domain_refs=["agriculture.crop_advisory", "health.malnutrition_watch",
                             "finance.parametric_insurance_eval"],
      )
    """
    domain:             EventDomain
    event_type:         str
    source:             str
    location:           KenyaLocation | SubnationalLocation = field(default_factory=KenyaLocation)
    severity:           EventSeverity  = EventSeverity.INFO
    data:               dict[str, Any] = field(default_factory=dict)
    cross_domain_refs:  list[str]      = field(default_factory=list)
    privacy_level:      str            = "aggregate"
    reality:            EventReality    = EventReality.REAL
    confidence:         EventConfidence = EventConfidence.UNKNOWN
    basis:              str            = ""   # optional: observed | derived | modeled | reported
    requires_action:    bool           = False
    event_id:           str            = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp:          str            = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> dict:
        return {
            "event_id":          self.event_id,
            "domain":            self.domain.value if isinstance(self.domain, EventDomain) else self.domain,
            "event_type":        self.event_type,
            "source":            self.source,
            "severity":          self.severity.value if isinstance(self.severity, EventSeverity) else self.severity,
            "timestamp":         self.timestamp,
            "location":          self.location.to_dict(),
            "data":              self.data,
            "cross_domain_refs": self.cross_domain_refs,
            "privacy_level":     self.privacy_level,
            "reality":           self.reality.value if isinstance(self.reality, EventReality) else self.reality,
            "confidence":        self.confidence.value if isinstance(self.confidence, EventConfidence) else self.confidence,
            "basis":             self.basis,
            "requires_action":   self.requires_action,
        }

    @classmethod
    def from_dict(cls, d: dict) -> CoordinationEvent:
        loc_data = d.get("location", {})
        loc: KenyaLocation | SubnationalLocation
        if "admin_1" in loc_data or "country" in loc_data:
            loc = SubnationalLocation(**{k: v for k, v in loc_data.items()
                                         if k in SubnationalLocation.__dataclass_fields__})
        else:  # legacy shape (county/county_code/sub_county) or empty
            loc = KenyaLocation(**{k: v for k, v in loc_data.items()
                                    if k in KenyaLocation.__dataclass_fields__})
        return cls(
            domain=EventDomain(d["domain"]),
            event_type=d["event_type"],
            source=d.get("source", "unknown"),
            location=loc,
            severity=EventSeverity(d.get("severity", "info")),
            data=d.get("data", {}),
            cross_domain_refs=d.get("cross_domain_refs", []),
            privacy_level=d.get("privacy_level", "aggregate"),
            # backward-compat: legacy records without provenance default to
            # REAL / UNKNOWN (a pre-provenance event is a real signal of unknown
            # declared confidence — never silently downgraded to DEMO).
            reality=EventReality(d.get("reality", "real")),
            confidence=EventConfidence(d.get("confidence", "unknown")),
            basis=d.get("basis", ""),
            requires_action=d.get("requires_action", False),
            event_id=d.get("event_id", str(uuid.uuid4())),
            timestamp=d.get("timestamp", datetime.now(timezone.utc).isoformat()),
        )
