"""
CoordinationEvent — standard schema for cross-domain coordination signals.

Mirrors schemas/coordination_event.json in AfriKaziOS.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class EventSeverity(str, Enum):
    INFO     = "info"
    WARNING  = "warning"
    ALERT    = "alert"
    CRITICAL = "critical"


class EventDomain(str, Enum):
    HEALTH       = "health"
    WATER        = "water"
    AGRICULTURE  = "agriculture"
    ENERGY       = "energy"
    TRANSPORT    = "transport"
    EDUCATION    = "education"
    PROCUREMENT  = "procurement"
    FINANCE      = "finance"
    CIVIC        = "civic"


@dataclass
class KenyaLocation:
    """Kenya-specific location with county code (1-47)."""
    county: str = ""
    county_code: int = 0
    sub_county: str = ""
    lat: float = 0.0
    lon: float = 0.0

    def to_dict(self) -> dict:
        return {k: v for k, v in self.__dict__.items() if v}


@dataclass
class CoordinationEvent:
    """
    A coordination signal crossing domain boundaries.

    Generated by any MCP server or sensor. Consumed by downstream
    domain handlers that need to act on the signal.

    Example — drought cascade:
      CoordinationEvent(
          domain=EventDomain.WATER,
          event_type="drought_alert",
          severity=EventSeverity.ALERT,
          location=KenyaLocation(county="Turkana", county_code=23),
          source="wapimaji-mcp",
          data={
              "ndvi_anomaly": -0.28,
              "spi_3month": -1.8,
              "rainfall_deficit_pct": 42,
          },
          cross_domain_refs=["agriculture.crop_advisory", "health.malnutrition_watch",
                             "finance.parametric_insurance_eval"],
      )
    """
    domain:             EventDomain
    event_type:         str
    source:             str
    location:           KenyaLocation = field(default_factory=KenyaLocation)
    severity:           EventSeverity  = EventSeverity.INFO
    data:               dict[str, Any] = field(default_factory=dict)
    cross_domain_refs:  list[str]      = field(default_factory=list)
    privacy_level:      str            = "aggregate"
    requires_action:    bool           = False
    event_id:           str            = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp:          str            = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> dict:
        return {
            "event_id":          self.event_id,
            "domain":            self.domain.value if isinstance(self.domain, EventDomain) else self.domain,
            "event_type":        self.event_type,
            "source":            self.source,
            "severity":          self.severity.value if isinstance(self.severity, EventSeverity) else self.severity,
            "timestamp":         self.timestamp,
            "location":          self.location.to_dict(),
            "data":              self.data,
            "cross_domain_refs": self.cross_domain_refs,
            "privacy_level":     self.privacy_level,
            "requires_action":   self.requires_action,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "CoordinationEvent":
        loc_data = d.get("location", {})
        loc = KenyaLocation(**{k: v for k, v in loc_data.items()
                                if k in KenyaLocation.__dataclass_fields__})
        return cls(
            domain=EventDomain(d["domain"]),
            event_type=d["event_type"],
            source=d.get("source", "unknown"),
            location=loc,
            severity=EventSeverity(d.get("severity", "info")),
            data=d.get("data", {}),
            cross_domain_refs=d.get("cross_domain_refs", []),
            privacy_level=d.get("privacy_level", "aggregate"),
            requires_action=d.get("requires_action", False),
            event_id=d.get("event_id", str(uuid.uuid4())),
            timestamp=d.get("timestamp", datetime.now(timezone.utc).isoformat()),
        )
